CREATE TABLE userGroupMembers
(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID() NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT NULL,
    userGroupId UUID REFERENCES userGroups(id) ON DELETE CASCADE,
    userId UUID UNIQUE REFERENCES users(id)  ON DELETE CASCADE
);

CREATE TRIGGER userGroupMembers_updated_at
    BEFORE UPDATE
    ON userGroupMembers
    FOR EACH ROW
    EXECUTE PROCEDURE updated_at_timestamp();